export enum AppCodes {
  // General Success
  SUCCESS = "SUCCESS",
  RESOURCE_CREATED = "RESOURCE_CREATED",
  RESOURCE_UPDATED = "RESOURCE_UPDATED",
  RESOURCE_DELETED = "RESOURCE_DELETED",

  // Authentication
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_VERIFICATION_EMAIL_SENT = "AUTH_VERIFICATION_EMAIL_SENT",
  AUTH_PASSWORD_RESET_SUCCESS = "AUTH_PASSWORD_RESET_SUCCESS",
  // Users
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
  USER_VERIFIED = "USER_VERIFIED",
  USER_INACTIVE = "USER_INACTIVE",
  // Validation
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED = "DATABASE_QUERY_FAILED",

  // External Services
  EXTERNAL_SERVICE_FAILURE = "EXTERNAL_SERVICE_FAILURE",
  PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR",

  // Server
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",

  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  PASSWORD_RESET_ATTEMPT_NON_EXISTENT_EMAIL = "PASSWORD_RESET_ATTEMPT_NON_EXISTENT_EMAIL",
  PASSWORD_RESET_ATTEMPT_INVALID_TOKEN = "PASSWORD_RESET_ATTEMPT_INVALID_TOKEN",
  RESEND_VERIFICATION_EMAIL_NON_EXISTENT_EMAIL = "RESEND_VERIFICATION_EMAIL_NON_EXISTENT_EMAIL",

  //landlord
  LANDLORDS_RETRIEVED = "LANDLORDS_RETRIEVED",
  LANDLORD_ALREADY_EXISTS = "LANDLORD_ALREADY_EXISTS",
  LANDLORD_NOT_FOUND = "LANDLORD_NOT_FOUND",
  LANDLORD_APPLICATION_SUBMITTED = "LANDLORD_APPLICATION_SUBMITTED",
  LANDLORD_APPLICATION_APPROVED = "LANDLORD_APPLICATION_APPROVED",
  LANDLORD_APPLICATION_REJECTED = "LANDLORD_APPLICATION_REJECTED",
  LANDLORD_PROFILE_RETRIEVED = "LANDLORD_PROFILE_RETRIEVED",
  LANDLORD_APPLICATIONS_RETRIEVED = "LANDLORD_APPLICATIONS_RETRIEVED",
  LANDLORD_INACTIVE = "LANDLORD_INACTIVE",
  LANDLORD_ALREADY_APPROVED = "LANDLORD_ALREADY_APPROVED",
  LANDLORD_ALREADY_REJECTED = "LANDLORD_ALREADY_REJECTED",
  //property
  PROPERTY_NOT_FOUND = "PROPERTY_NOT_FOUND",
  PROPERTY_CREATED = "PROPERTY_CREATED",
  PROPERTY_UPDATED = "PROPERTY_UPDATED",
  PROPERTY_DELETED = "PROPERTY_DELETED",
}
